apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - image: grafana/loki:2.3.0
        imagePullPolicy: IfNotPresent
        name: loki
        ports:
        - containerPort: 3100
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/loki/local-config.yaml
          name: loki-config-volume
          subPath: loki-config.yaml
      volumes:
      - configMap:
          name: loki-configmap
        name: loki-config-volume
