apiVersion: v1
kind: Service
metadata:
  labels:
    app: loki
  name: loki
  namespace: default
spec:
  ports:
  - nodePort: 30523
    port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: loki
  type: NodePort
