apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: loki
  name: loki
  namespace: default
spec:
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - image: grafana/loki:2.5.0
        imagePullPolicy: IfNotPresent
        name: loki
        ports:
        - containerPort: 3100
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/loki/local-config.yaml
          name: loki-config
          subPath: loki-config.yaml
        - name: loki-pv
          mountPath: /loki          
      volumes:
      - configMap:
          name: loki-config
        name: loki-config
      - name: loki-pv
        persistentVolumeClaim:
          claimName: loki-pvc

